version: "3.9"

services:
  cloudproxy:
    restart: always
    build: 
      context: .
      image: quinndt/cloudproxy
      # # If the example below is implemented this should work, although I havent tried the
      # # harvester myself and have no idea if "<domain>" is the right syntax, it shows in examples
      # args:
      #   CAPTCHA_SOLVER: harvester
      #   HARVESTER_ENDPOINT: https://harvester:5000/<domain>/token
    ports:
      # Map host (8191) to container (8191)
      - 8191:8191

  # This can be expanded upon to automatically start a captcha harvester and connect them on the same network
  # However the harvester isnt dockerised yet.

  # # Example:
  # harvester:
  #   build:
  #     context: .
  #     # Assuming this exists & exposes port 5000 as the harvester
  #     dockerfile: harvester.Dockerfile
  #     # it is also possible to pull the image from docker hub
  #     image: username/image
